language: scala

sudo: required

services: docker

jdk: openjdk11

scala: 2.12.8

env:
  global:
    - secure: "bARq09zUgTg6hzUAOaRJ0ntfbpWJRjuEe4zoDRMaW9uzkGE7e0ZiYVuvcb5BCJ+sUwtzke/+vtv+JBML7tpxxMJkXkEJZGZ77PdIuFRS7+h/bD6JGZQQMC2rU9JuKSc24O1qEobQa8Pj9tIvUkxp7XZDP/fKTnHtjdMBHeErs7DWFoIEVTVdovxYZGy6fHp4sI9jo5e4VC2XIA1iMWTnACudqUvFUJ4E1Gi6F9OzhbGlICbeofeHs3PnmYdqhn5Yqx9Z2FPuxh+qewadUMK2jg1dxUmHfuxfCyvrvhDMmPxrUbThZKSrGiULVoRLCPR9h5VHHhOzm28FRZRnCLqr8d1RsCHiLeeGPm7W7wv4sx7y9ir76s3tsrASwMxRTy/d0CDAZQUjI9ScYp2dIknz/OByLSzeeMrMUvKmOR1ubN/sPoxS7odls/IGQ/TDhkbOC49X9nho5y84pl7MHg1tBcdek/rT/itEEWZwj4jQ6s8lZUqgqwpPpLw0JOv782FDV73BbOc6ufH9TjtapB5PhiVnCV9tzGnGoDSSB0cgAe+6KR3vkCOvixh1adWJt3GQfsjrobqp/CWoOC19C0kUo4sweDovnT055/k1oFzvdBLYpuhXmYx/4yolBJzOIGdz/KY4meyIRa2VmR9s9RecOv4GSIjCH8jK7wRDcqxDfGI="
    - secure: "OqVd+wDLARXI2Cd+AK/cYSp4bp8FBlNgHyIF2gNY/CJnxHoSgwHiNa9SNP0M7wrYck9DReq86AeXa9jzxKiKKbx10nIYR3phjnBS9ik61Kv9CtyyX6A7DSiXMMvR71fL1Ho7ECRH7CAHaYeuwt5snjdQYntrplkTZW7uKUQv0+m0RgH20c5h49Jpfp050YU/yzgBCYNHgTyntVjjDIHS7kmjNYH5n2ynDUVo3BDXhc/+OXAL485vUOrLLLr4Kxwf+k01ziX5JQxsR+jH7WCLlcUG1t6FHDJ4tMw6dWvyGM/ZmheatRH2N8bIi6XQKOeG6wRagKUFR3IfVD3vJbdmZz31utRXUEawsufp73hImfXMh1BZGvmepP9qMroOzjq6SJ5K6efSdw61isVl/jPZHAI1Y1GfisJny5sGEfW5oElOlDjLgeeOM+FWo/NocZHeDI17Df/7gOfgnW0PY2jcrcwxqVbm3/u9y6L5z8IyzEkR/NOMYTx9eHGlcWlePPewfJPh1rcd1uWFN3XiPCMsQWZBxMnSdEkncwVkdJv+JSdaBAbBmwE2gAD9uYqxH7Ri2Ikr5TT8yMOGNZTof1LFrGeThRAUcIheYtXQf3qxaphsACl42275tpX1OPGm0co2n5xyP4lB6poUt79e7MtwYmDdFRgm1+LUufeakDTMGXs="


cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete

notifications:
  email:
    on_success: never

before_script:
  - sbt -J-Dsbt.log.noformat=true dependencyTree | PROJECT_GROUP_KEY=godfather YAMORY_API_KEY="${YAMORY_API_KEY}" bash -c "$(curl -sSf -L https://localscanner.yamory.io/script/sbt)"
  - echo ${DOCKERHUB_PASSWORD} | docker login -u cndjpintegrate --password-stdin
script:
  - sbt test
  - sbt assembly
  - docker build -t cndjp/godfather:$(git rev-parse HEAD) .
  - if [[ "${TRAVIS_BRANCH}" = "master" ]]; then docker push cndjp/godfather:$(git rev-parse HEAD); fi