language: scala

sudo: required

services: docker

jdk: openjdk11

scala: 2.12.8

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete

notifications:
  email:
    on_success: never

script:
  - sbt test
  - sbt assembly
  - docker build -t cndjp/godfather:latest .